### ISSUE TITLE
404 on own page - can't create box

### ISSUE THREAD

**Issue by MatthewRobo** [izenn/padbox#11]
The following is what the webpage shows me:

> Your box has been processed and is available [here](https://padbox.izenn.net/box/339063343.html)
> A simplified mobile friendly box list can be found [here](https://padbox.izenn.net/m/339063343.html)
> Processor Output:
> 
> `Can't locate JSON.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./pad.pl line 4.`
> `BEGIN failed--compilation aborted at ./pad.pl line 4.`

These were the files I tried to upload, in order:
[captured_data.txt](https://github.com/izenn/padbox/files/4523740/captured_data.txt)
[pad.json](https://github.com/izenn/padbox/files/4523730/pad.txt)
[captured_data.txt](https://github.com/izenn/padbox/files/4523729/captured_data.txt)

**Comment by izenn** [comment]
looks like when the hosting provider moved me to a new server they don't have a perl module installed that was on the last one.  working on this now

**Comment by izenn** [comment]
fixed
