### ISSUE TITLE
Cards with 3-digit IDs are missing images in the Friend Leader tab.

### ISSUE THREAD

**Issue by Raijinili** [izenn/padbox#4]
For example, 890 uses [card_0890.png](http://padbox.izenn.net/images/cards/card_0890.png), which is a 404. I suspect all cards with <4 digits have this issue. The correct image is [card_00890.png](http://padbox.izenn.net/images/cards/card_00890.png). Needs a zero-fill to 5 for consistency.

**Comment by izenn** [comment]
good catch.  fixed in 71a2a817
