### ISSUE TITLE
https certs expired on site

### ISSUE THREAD

**Issue by Alex-Michie** [izenn/padbox#7]
> Websites prove their identity via certificates, which are valid for a set time period. The certificate for padbox.izenn.net expired on 11/25/2019.
> 
>Error code: SEC_ERROR_EXPIRED_CERTIFICATE

i know thi isnt technically an issue with the repo but an issue with the the config on the site but... hopefully this is the right spot for it anyway

**Comment by izenn** [comment]
fixed -- thanks for catching that!!

**Comment by Alex-Michie** [comment]
its happened again, hopefully something easy to fix

**Comment by izenn** [comment]
opened a support ticket with the hosting company.  something is mucked up on their end

**Comment by izenn** [comment]
fixed
