### ISSUE TITLE
card database not updating correctly?

### ISSUE THREAD

**Issue by Alex-Michie** [izenn/padbox#8]
this is a combination of an assumption on my part as to how things work and alot of symptoms ive found, all which can be viewed on my box's page: https://padbox.izenn.net/box/312725316.html

some creatures have the wrong picture:
for example my kiriko (1973) shows up with kagato (1983)'s picture in the rem+ tab and the team/friends tab

or searching "kag" in my mats tab shows 3 creatures which have the wrong picture for them (by number: 1982, 1944, 1945)
for these cases the awakenings/stats/names/links all seem to be correct so its just the picture that got shuffled at some point?
this was the case before and after i uploaded new box data

missing name data for senri (not sure if others are effected, this is the only one i saw)
the name was shown as "*****" stats/ picture /etc seem to be right otherwise

missing stats:
my shiki(5578) im assuming has no stats data in your db and has the following issues (im assuming this extend to other creatures, but i only have samurai showdown examples, which i guess makes sense)
- name shows up as "????"
- shown as having the wrong attributes (mono fire/balanced)
- no awakenings shown (but the super awakening is shown properly?)
- skill/rarity/mp value isnt shown properly (+'s, the link, picture, and level is though)
- several showdown characters show up as mats when they arent, even if they feel like it

when i uploaded my box with the samurai showdown characters i did pick the ilmina link option, so im not sure if thats what caused some of the newer cards to update correctly/att all, as im assuming your using those links to update your card db for when new cards are added

also as an addendum since this regressed(?) again and its not a huge deal to me, but is still something is: the link page(results.php) after updating my box linkekd specifically to your box again, rather than the id i supplied. i have both the mobile link and the desktop link bookmarked so its not a big deal to me, but...

**Comment by izenn** [comment]
I’ll look into this tonight. When was the last time you updated your box json?

**Comment by izenn** [comment]
just a quick look shows that it looks like the cardcut script is having issues which is why the pictures are wrong.  I'll work through the rest of the issues with your json later (i'm wondering if you updated your box before i updated the database)

**Comment by Alex-Michie** [comment]
i had updated it either today or last night? i believe it was this morning though, so rather recently.

i didnt have an update for it with any of the samurai showdown characters till after the collab was totally over if thats what your wondering about though

**Comment by izenn** [comment]
yeah -- i just wanted to make sure it was fresh since i did a push for assets just the other day when we had the data download

**Comment by izenn** [comment]
card images are fixed -- when i switched from the JP to USA data the images changed a bit and omitted some lines. (356c04010de396ba30b8e9460ab6d9aa606dd0dd)

Also i fixed the box link issue

remaining:
missing data for senri and shiki - not sure why this is happening, i'll have to dig into the database (i use the same database as mirubot)

**Comment by izenn** [comment]
i can now generate the db myself.  db has been updated and i re-ran your processing.  everything looks good (both senri and Shiki are showing up with the right stuff now).  Special thanks to tactical_retreat
